// =============================================================================
// Project: Formal Verification of a RISC-V Microprocessor
// Module: rv32i_bind
// Description: Binds the SystemVerilog Assertions module to the core module.
// =============================================================================

bind rv32i_core rv32i_sva u_rv32i_sva (
    .clk(clk),
    .rst_n(rst_n),
    .imem_addr(imem_addr),
    .imem_rdata(imem_rdata),
    .imem_req(imem_req),
    .dmem_addr(dmem_addr),
    .dmem_wdata(dmem_wdata),
    .dmem_we(dmem_we),
    .dmem_be(dmem_be),
    .dmem_rdata(dmem_rdata),
    .dmem_req(dmem_req),
    .if_pc(if_pc),
    .next_pc(next_pc),
    .pipeline_stall(pipeline_stall),
    .branch_taken(branch_taken),
    .flush_if_id(flush_if_id),
    .flush_id_ex(flush_id_ex),
    .id_pc(id_pc),
    .id_instr(id_instr),
    .id_rs1(id_rs1),
    .id_rs2(id_rs2),
    .id_rd(id_rd),
    .id_imm(id_imm),
    .id_alu_op(id_alu_op),
    .id_alu_src_sel(id_alu_src_sel),
    .id_dmem_we(id_dmem_we),
    .id_dmem_re(id_dmem_re),
    .id_reg_write(id_reg_write),
    .id_wb_src(id_wb_src),
    .rf_rdata1(rf_rdata1),
    .rf_rdata2(rf_rdata2),
    .ex_pc(ex_pc),
    .ex_rs1(ex_rs1),
    .ex_rs2(ex_rs2),
    .ex_rd(ex_rd),
    .ex_alu_op(ex_alu_op),
    .ex_alu_src_sel(ex_alu_src_sel),
    .ex_alu_out(ex_alu_out),
    .ex_forwarded_rs1(ex_forwarded_rs1),
    .ex_forwarded_rs2(ex_forwarded_rs2),
    .forward_a(forward_a),
    .forward_b(forward_b),
    .ex_dmem_re(ex_dmem_re),
    .ex_dmem_we(ex_dmem_we),
    .ex_reg_write(ex_reg_write),
    .ex_imm(ex_imm),
    .mem_pc(mem_pc),
    .mem_rd(mem_rd),
    .mem_alu_out(mem_alu_out),
    .mem_reg_write(mem_reg_write),
    .wb_pc(wb_pc),
    .wb_rd(wb_rd),
    .wb_alu_out(wb_alu_out),
    .wb_reg_write(wb_reg_write),
    .wb_wdata(wb_wdata),
    .reg_file_val_1(reg_file[1])
);
